{% if alpine_version is not defined or alpine_version == 'latest' %}
FROM alpine
{% else %}
FROM alpine:{{alpine_version}}
{% endif %}

LABEL maintainer "https://github.com/borisskert/ansible-minecraft"

RUN apk add --no-cache -U \
  bash \
  curl \
{% if openjdk_version is not defined or openjdk_version == 'latest' %}
  openjdk8-jre
{% else %}
  openjdk8-jre={{openjdk_version}}
{% endif %}

RUN adduser -DHs /sbin/nologin -u {{minecraft_user_uid}} minecraft

RUN mkdir -p /data && \
    curl -o /minecraft_server.jar "{{download_info.url}}"; \
    echo "{{download_info.sha1}} /minecraft_server.jar" | sha1sum --check -; \
    chown -R minecraft:minecraft /data

COPY ./start /start
RUN	chmod +x /start

USER minecraft

EXPOSE 25565

VOLUME ["/data"]

ENTRYPOINT ["/start"]
