---
- hosts: test_machine
  become: yes

  pre_tasks:
  - apt:
      name: python-docker
      update_cache: yes

  post_tasks:
  - apt:
      name: python-docker
      state: absent
      purge: yes

  roles:
  - role: '.'
    version: 1.12.2
    volume: /srv/docker/minecraft/data
    publish:
      port: 25565
      interface: 0.0.0.0
