---
- name: Create docker working directory
  file:
    path: "{{working_directory}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create dockerimage directory
  file:
    path: "{{docker_image.path}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Template dockerfile
  template:
    src: ./docker/Dockerfile.j2
    dest: "{{docker_image.path}}/Dockerfile"
    owner: root
    group: root
    mode: 0644
  register: dockerfile

- name: Copy docker entrypoint start script
  copy:
    src: ./docker/start
    dest: "{{docker_image.path}}/start"
    owner: root
    group: root
    mode: 0755
  register: dockerimage_files

- name: Build dockerimage
  docker_image:
    build:
      path: "{{docker_image.path}}"
      pull: no
    name: "{{docker_image.name}}"
    tag: "{{version_to_be_installed}}"
    source: build
    force_source: "{{ dockerfile.changed or force_build or dockerimage_files.changed }}"
  register: dockerimage
