---
- name: create docker working directory
  file:
    path: "{{docker.workingdir}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create java dockerimage directory
  file:
    path: "{{docker_images.java.path}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: template base dockerfile
  template:
    src: ./docker/java/Dockerfile
    dest: "{{docker_images.java.path}}/Dockerfile"
    owner: root
    group: root
    mode: 0554
  register: base_dockerfile

- name: build base dockerimage
  docker_image:
    path: "{{docker_images.java.path}}"
    name: "{{docker_images.java.name}}:{{docker_images.java.tag}}"
    force: "{{docker_images.java.force_build or base_dockerfile.changed}}"
  register: base_dockerimage

- name: create dockerimage directory
  file:
    path: "{{docker_images.minecraft.path}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: template dockerfile
  template:
    src: ./docker/Dockerfile
    dest: "{{docker_images.minecraft.path}}/Dockerfile"
    owner: root
    group: root
    mode: 0554
  register: dockerfile

- name: copy dockerimage files
  copy:
    src: ./docker/
    dest: "{{docker_images.minecraft.path}}"
    owner: root
    group: root
    mode: 0755
  register: dockerimage_files

- name: build image
  docker_image:
    path: "{{docker_images.minecraft.path}}"
    name: "{{docker_images.minecraft.name}}:{{docker_images.minecraft.tag}}"
    force: "{{base_dockerimage.changed or docker_images.minecraft.force_build or dockerfile.changed or dockerimage_files.changed}}"
    pull: False
  register: dockerimage
