---
- name: Create volume directories
  file:
    path: "{{item.value}}"
    state: directory
    owner: "{{minecraft_user_uid}}"
    group: "{{minecraft_user_uid}}"
    mode: '0775'
  when: item.value is defined and item.value != ''
  with_dict: "{{docker_container.volumes}}"
